"""
generator.py — Solution Brief & Export Utilities

Generates a professional English solution brief in Markdown and provides
BytesIO export for Streamlit's download_button.
"""

from io import BytesIO
from datetime import datetime


# ── Chinese → English value mapping for brief display ─────────────────────

_MARKET_EN = {
    "北美": "North America",
    "欧洲": "Europe",
    "东南亚": "Southeast Asia",
    "中东": "Middle East",
}

_SCENARIO_EN = {
    "户外运动": "Outdoor Sports",
    "商务办公": "Business Office",
    "日常通勤": "Daily Commute",
    "游戏娱乐": "Gaming & Entertainment",
    "旅行出差": "Travel",
}

_USECASE_EN = {
    "音质表现": "Audio Quality",
    "续航能力": "Battery Life",
    "快充技术": "Fast Charging",
    "便携设计": "Portable Design",
    "智能互联": "Smart Connectivity",
    "运动健身": "Sports Fitness",
    "商务兼容": "Business Compatibility",
}

_BUDGET_EN = {
    "入门": "Low",
    "中端": "Medium",
    "高端": "High",
}


def _en(val, mapping):
    return mapping.get(val, val)


# ── Template ────────────────────────────────────────────────────────────────

BRIEF_TEMPLATE = """# Solution Brief — Overseas GTM Workbench

**Generated:** {timestamp}

---

## Customer Profile

| Field | Value |
|-------|-------|
| **Target Market** | {market} |
| **Use Scenario** | {use_scenario} |
| **Core Need** | {use_case} |
| **Budget Range** | {budget} |

---

## Recommended Products

{product_list}

---

## Solution Overview

This tailored solution addresses a **{use_scenario}** scenario in the
**{market}** market, with a primary focus on **{use_case}** within a
**{budget}** budget range.

{need_paragraph}

The bundle comprises **{count}** carefully selected product{plural} that
deliver a cohesive, high-performance user experience.

{value_proposition}

---

*This brief was automatically generated by Overseas GTM Workbench on {timestamp}.*
"""


_NEED_BLOCKS = {
    "Audio Quality": (
        "Your emphasis on audio quality is addressed with products featuring "
        "high-resolution codecs (aptX HD / LDAC), premium driver architecture, "
        "and advanced acoustic engineering — delivering a truly immersive "
        "listening experience."
    ),
    "Battery Life": (
        "Your battery-life requirements are met with devices engineered for "
        "all-day endurance: high-capacity cells, low-power chipsets, and "
        "intelligent power management keep you going without interruption."
    ),
    "Fast Charging": (
        "Your need for fast charging is satisfied through GaN technology, "
        "high-wattage Power Delivery support, and multi-device charging "
        "capabilities — getting you back to full power in record time."
    ),
    "Portable Design": (
        "Your preference for portable design is reflected in products that are "
        "ultra-compact, lightweight, and thoughtfully engineered for maximum "
        "mobility without compromising performance or durability."
    ),
    "Smart Connectivity": (
        "Your smart-connectivity needs are met with products featuring "
        "seamless Bluetooth multipoint, companion-app controls, "
        "cross-platform compatibility, and rich ecosystem integration."
    ),
    "Sports Fitness": (
        "Your sports and fitness requirements are addressed with sweatproof "
        "designs, secure ergonomic fit, real-time activity tracking, and "
        "durable builds that keep up with the most demanding workouts."
    ),
    "Business Compatibility": (
        "Your business-compatibility needs are met with professional-grade "
        "connectivity, universal device support, crisp call quality, and a "
        "refined aesthetic suitable for any workplace."
    ),
}

_VALUE_BLOCKS = {
    "Low": (
        "**Expected value:** A cost-effective selection that delivers "
        "essential features at an accessible price — reliable performance "
        "without compromising core functionality."
    ),
    "Medium": (
        "**Expected value:** A well-balanced selection offering strong "
        "features, dependable build quality, and room to grow — ideal for "
        "discerning everyday users."
    ),
    "High": (
        "**Expected value:** A flagship-grade selection that represents "
        "the best in class: premium materials, advanced capabilities, and "
        "an uncompromised experience for the most demanding users."
    ),
}


def generate_solution_brief(
    market: str,
    use_scenario: str,
    use_case: str,
    budget: str,
    products: list[dict],
) -> str:
    """Render a complete English solution brief as Markdown."""
    # Map Chinese UI values to English for the brief
    market_en = _en(market, _MARKET_EN)
    scenario_en = _en(use_scenario, _SCENARIO_EN)
    usecase_en = _en(use_case, _USECASE_EN)
    budget_en = _en(budget, _BUDGET_EN)

    product_lines = [
        f"{i}. **{p['name']}** ({p['category']}) — {p['description']}"
        for i, p in enumerate(products, 1)
    ]
    product_list = "\n".join(product_lines) if product_lines else "*No products matched.*"

    need_paragraph = _NEED_BLOCKS.get(
        usecase_en,
        f"Your focus on **{usecase_en}** guided our product selection to ensure "
        "the solution aligns perfectly with your priorities.",
    )

    value_proposition = _VALUE_BLOCKS.get(
        budget_en,
        "**Expected value:** This solution is designed to meet your "
        "requirements effectively and efficiently.",
    )

    return BRIEF_TEMPLATE.format(
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
        market=market_en,
        use_scenario=scenario_en,
        use_case=usecase_en,
        budget=budget_en,
        product_list=product_list,
        count=len(products),
        plural="s" if len(products) != 1 else "",
        need_paragraph=need_paragraph,
        value_proposition=value_proposition,
    )


def export_to_bytesio(markdown_text: str) -> BytesIO:
    """Wrap Markdown content in a BytesIO stream for download."""
    bio = BytesIO()
    bio.write(markdown_text.encode("utf-8"))
    bio.seek(0)
    return bio


def suggest_filename(market: str, use_scenario: str) -> str:
    """Generate a meaningful filename for the exported brief."""
    # Map Chinese to English for filename
    market_en = _en(market, _MARKET_EN)
    scenario_en = _en(use_scenario, _SCENARIO_EN)
    slug_market = market_en.lower().replace(" ", "-")
    slug_scenario = scenario_en.lower().replace(" ", "-")
    date_str = datetime.now().strftime("%Y%m%d")
    return f"solution-brief_{slug_market}_{slug_scenario}_{date_str}.md"
